<?php

namespace AppBundle\Repository;

/**
 * Product_bookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_bookRepository extends \Doctrine\ORM\EntityRepository
{
}
