<?php

namespace AppBundle\Repository;

/**
 * StoreProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreProductRepository extends \Doctrine\ORM\EntityRepository
{
}
