<?php

namespace AppBundle\Repository;

/**
 * SubcatgoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcatgoryRepository extends \Doctrine\ORM\EntityRepository
{
}
