<?php

namespace AppBundle\Repository;

/**
 * users1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class users1Repository extends \Doctrine\ORM\EntityRepository
{
}
